apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  namespace: core-platform
  labels:
    app: account-service
    tier: proxy-mesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        # 1. THE PLATFORM DEFENSE SIDECAR: CHRONOS-GUARD
        - name: chronos-guard-sidecar
          image: vamsikrishnao/chronos-guard:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc-proxy
            - containerPort: 9090
              name: metrics
          env:
            - name: REDIS_ADDR
              value: "redis-master:6379"
            - name: REDIS_PASSWORD
              value: "secure_token_cluster_pass"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          startupProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 3
          livenessProbe:
            grpc:
              port: 50051
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false

        # 2. THE CORE APPLICATION SERVICE
        - name: upstream-app
          image: vamsikrishnao/account-service:v2.4.0
          env:
            - name: RATE_LIMIT_PROXY_URL
              value: "127.0.0.1:50051"
            - name: ENVIRONMENT
              value: "production"
          resources:
            limits:
              cpu: "2000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8080
              name: app-http