// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/chronos/v1/guard.proto

package chronosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckBudgetResponse_Action int32

const (
	CheckBudgetResponse_ACTION_UNSPECIFIED CheckBudgetResponse_Action = 0
	CheckBudgetResponse_ACTION_ALLOW       CheckBudgetResponse_Action = 1 // Execution loop safe
	CheckBudgetResponse_ACTION_THROTTLE    CheckBudgetResponse_Action = 2 // Approaching threshold; inject deliberate delay
	CheckBudgetResponse_ACTION_BLOCK       CheckBudgetResponse_Action = 3 // Circuit breaker tripped; abort step
)

// Enum value maps for CheckBudgetResponse_Action.
var (
	CheckBudgetResponse_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ALLOW",
		2: "ACTION_THROTTLE",
		3: "ACTION_BLOCK",
	}
	CheckBudgetResponse_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ALLOW":       1,
		"ACTION_THROTTLE":    2,
		"ACTION_BLOCK":       3,
	}
)

func (x CheckBudgetResponse_Action) Enum() *CheckBudgetResponse_Action {
	p := new(CheckBudgetResponse_Action)
	*p = x
	return p
}

func (x CheckBudgetResponse_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckBudgetResponse_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chronos_v1_guard_proto_enumTypes[0].Descriptor()
}

func (CheckBudgetResponse_Action) Type() protoreflect.EnumType {
	return &file_proto_chronos_v1_guard_proto_enumTypes[0]
}

func (x CheckBudgetResponse_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckBudgetResponse_Action.Descriptor instead.
func (CheckBudgetResponse_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_chronos_v1_guard_proto_rawDescGZIP(), []int{1, 0}
}

type CheckBudgetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                   // Multi-tenant context isolation
	RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`                            // Execution context tracing identifier
	TokensSpent    int64                  `protobuf:"varint,3,opt,name=tokens_spent,json=tokensSpent,proto3" json:"tokens_spent,omitempty"`         // Cumulative delta of tokens consumed this step
	StateSignature string                 `protobuf:"bytes,4,opt,name=state_signature,json=stateSignature,proto3" json:"state_signature,omitempty"` // SHA256/MD5 representation of current agent states
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckBudgetRequest) Reset() {
	*x = CheckBudgetRequest{}
	mi := &file_proto_chronos_v1_guard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBudgetRequest) ProtoMessage() {}

func (x *CheckBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_guard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBudgetRequest.ProtoReflect.Descriptor instead.
func (*CheckBudgetRequest) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_guard_proto_rawDescGZIP(), []int{0}
}

func (x *CheckBudgetRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckBudgetRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CheckBudgetRequest) GetTokensSpent() int64 {
	if x != nil {
		return x.TokensSpent
	}
	return 0
}

func (x *CheckBudgetRequest) GetStateSignature() string {
	if x != nil {
		return x.StateSignature
	}
	return ""
}

type CheckBudgetResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Action        CheckBudgetResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=chronos.v1.CheckBudgetResponse_Action" json:"action,omitempty"`
	Reason        string                     `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Diagnostic metadata message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBudgetResponse) Reset() {
	*x = CheckBudgetResponse{}
	mi := &file_proto_chronos_v1_guard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBudgetResponse) ProtoMessage() {}

func (x *CheckBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chronos_v1_guard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBudgetResponse.ProtoReflect.Descriptor instead.
func (*CheckBudgetResponse) Descriptor() ([]byte, []int) {
	return file_proto_chronos_v1_guard_proto_rawDescGZIP(), []int{1}
}

func (x *CheckBudgetResponse) GetAction() CheckBudgetResponse_Action {
	if x != nil {
		return x.Action
	}
	return CheckBudgetResponse_ACTION_UNSPECIFIED
}

func (x *CheckBudgetResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_chronos_v1_guard_proto protoreflect.FileDescriptor

const file_proto_chronos_v1_guard_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/chronos/v1/guard.proto\x12\n" +
	"chronos.v1\"\x94\x01\n" +
	"\x12CheckBudgetRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12!\n" +
	"\ftokens_spent\x18\x03 \x01(\x03R\vtokensSpent\x12'\n" +
	"\x0fstate_signature\x18\x04 \x01(\tR\x0estateSignature\"\xc8\x01\n" +
	"\x13CheckBudgetResponse\x12>\n" +
	"\x06action\x18\x01 \x01(\x0e2&.chronos.v1.CheckBudgetResponse.ActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Y\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_ALLOW\x10\x01\x12\x13\n" +
	"\x0fACTION_THROTTLE\x10\x02\x12\x10\n" +
	"\fACTION_BLOCK\x10\x032^\n" +
	"\fGuardService\x12N\n" +
	"\vCheckBudget\x12\x1e.chronos.v1.CheckBudgetRequest\x1a\x1f.chronos.v1.CheckBudgetResponseBCZAgithub.com/vamsikrishnao/chronos-guard/proto/chronos/v1;chronosv1b\x06proto3"

var (
	file_proto_chronos_v1_guard_proto_rawDescOnce sync.Once
	file_proto_chronos_v1_guard_proto_rawDescData []byte
)

func file_proto_chronos_v1_guard_proto_rawDescGZIP() []byte {
	file_proto_chronos_v1_guard_proto_rawDescOnce.Do(func() {
		file_proto_chronos_v1_guard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chronos_v1_guard_proto_rawDesc), len(file_proto_chronos_v1_guard_proto_rawDesc)))
	})
	return file_proto_chronos_v1_guard_proto_rawDescData
}

var file_proto_chronos_v1_guard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_chronos_v1_guard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_chronos_v1_guard_proto_goTypes = []any{
	(CheckBudgetResponse_Action)(0), // 0: chronos.v1.CheckBudgetResponse.Action
	(*CheckBudgetRequest)(nil),      // 1: chronos.v1.CheckBudgetRequest
	(*CheckBudgetResponse)(nil),     // 2: chronos.v1.CheckBudgetResponse
}
var file_proto_chronos_v1_guard_proto_depIdxs = []int32{
	0, // 0: chronos.v1.CheckBudgetResponse.action:type_name -> chronos.v1.CheckBudgetResponse.Action
	1, // 1: chronos.v1.GuardService.CheckBudget:input_type -> chronos.v1.CheckBudgetRequest
	2, // 2: chronos.v1.GuardService.CheckBudget:output_type -> chronos.v1.CheckBudgetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chronos_v1_guard_proto_init() }
func file_proto_chronos_v1_guard_proto_init() {
	if File_proto_chronos_v1_guard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chronos_v1_guard_proto_rawDesc), len(file_proto_chronos_v1_guard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chronos_v1_guard_proto_goTypes,
		DependencyIndexes: file_proto_chronos_v1_guard_proto_depIdxs,
		EnumInfos:         file_proto_chronos_v1_guard_proto_enumTypes,
		MessageInfos:      file_proto_chronos_v1_guard_proto_msgTypes,
	}.Build()
	File_proto_chronos_v1_guard_proto = out.File
	file_proto_chronos_v1_guard_proto_goTypes = nil
	file_proto_chronos_v1_guard_proto_depIdxs = nil
}
