// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/chronos/v1/guard.proto

package chronosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuardService_CheckBudget_FullMethodName = "/chronos.v1.GuardService/CheckBudget"
)

// GuardServiceClient is the client API for GuardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuardServiceClient interface {
	// Evaluates a single execution step of an AI Agent to enforce guardrails.
	CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error)
}

type guardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuardServiceClient(cc grpc.ClientConnInterface) GuardServiceClient {
	return &guardServiceClient{cc}
}

func (c *guardServiceClient) CheckBudget(ctx context.Context, in *CheckBudgetRequest, opts ...grpc.CallOption) (*CheckBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBudgetResponse)
	err := c.cc.Invoke(ctx, GuardService_CheckBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuardServiceServer is the server API for GuardService service.
// All implementations must embed UnimplementedGuardServiceServer
// for forward compatibility.
type GuardServiceServer interface {
	// Evaluates a single execution step of an AI Agent to enforce guardrails.
	CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error)
	mustEmbedUnimplementedGuardServiceServer()
}

// UnimplementedGuardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuardServiceServer struct{}

func (UnimplementedGuardServiceServer) CheckBudget(context.Context, *CheckBudgetRequest) (*CheckBudgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBudget not implemented")
}
func (UnimplementedGuardServiceServer) mustEmbedUnimplementedGuardServiceServer() {}
func (UnimplementedGuardServiceServer) testEmbeddedByValue()                      {}

// UnsafeGuardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuardServiceServer will
// result in compilation errors.
type UnsafeGuardServiceServer interface {
	mustEmbedUnimplementedGuardServiceServer()
}

func RegisterGuardServiceServer(s grpc.ServiceRegistrar, srv GuardServiceServer) {
	// If the following call panics, it indicates UnimplementedGuardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuardService_ServiceDesc, srv)
}

func _GuardService_CheckBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuardServiceServer).CheckBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuardService_CheckBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuardServiceServer).CheckBudget(ctx, req.(*CheckBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuardService_ServiceDesc is the grpc.ServiceDesc for GuardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chronos.v1.GuardService",
	HandlerType: (*GuardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckBudget",
			Handler:    _GuardService_CheckBudget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chronos/v1/guard.proto",
}
